apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nn-predictor
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alexvidi/azure-aks-fastapi-terraform.git
    targetRevision: HEAD
    path: helm/nn-predictor
    helm:
      releaseName: nn-predictor

  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: nn-predictor-deploy
      namespace: fastapi
      jsonPointers:
        - /spec/replicas

